/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vpl.gui;

import vpl.gui.gl.GLDrawingHandler;
import vpl.gui.gl.GLControlHandler;
import vpl.gui.shapes.Ball;
import vpl.gui.shapes.Cuboid;
import vpl.gui.shapes.Cube;
import vpl.gui.shapes.Shape;
import com.jogamp.opengl.util.Animator;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.awt.GLCanvas;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import lombok.Getter;
import lombok.Setter;
import vpl.math.Triple;
import vpl.physics.controller.Model;
import vpl.gui.shapes.Cone;
import vpl.gui.shapes.Cyllinder;
import vpl.physics.controller.ControllerStub;
import vpl.physics.shapes.BallShape;
import vpl.physics.shapes.ConeShape;
import vpl.physics.shapes.CuboidShape;
import vpl.physics.shapes.CyllinderShape;

public class RootJPanel extends javax.swing.JPanel {

    private Animator animator;
    
    public RootJPanel() {
        initComponents();
    }
        
    public void startAnimator() {
        if (animator == null) {
            animator = new Animator(this.glCanvas);
        }
        animator.start();
    }
    
    public void stopAnimator() {
        if (animator != null) {
            animator.stop();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerJPanel = new javax.swing.JPanel();
        glCanvas = new vpl.gui.gl.VplGLCanvas();
        experimentExecutionJPanel1 = new vpl.gui.ExperimentExecutionJPanel();
        leftJPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addObjectJPanel2 = new vpl.gui.AddObjectJPanel();
        addForceJPanel1 = new vpl.gui.AddForceJPanel();
        rightJPanel = new javax.swing.JPanel();
        objectListJPanel1 = new vpl.gui.ObjectListJPanel();

        setLayout(new java.awt.BorderLayout());

        centerJPanel.setMinimumSize(new java.awt.Dimension(200, 200));
        centerJPanel.setLayout(new java.awt.BorderLayout());
        centerJPanel.add(glCanvas, java.awt.BorderLayout.CENTER);
        centerJPanel.add(experimentExecutionJPanel1, java.awt.BorderLayout.PAGE_END);

        add(centerJPanel, java.awt.BorderLayout.CENTER);

        leftJPanel.setPreferredSize(new java.awt.Dimension(250, 676));
        leftJPanel.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.addTab("Object properties", addObjectJPanel2);
        jTabbedPane1.addTab("Force properties", addForceJPanel1);

        leftJPanel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(leftJPanel, java.awt.BorderLayout.WEST);

        rightJPanel.setPreferredSize(new java.awt.Dimension(170, 676));
        rightJPanel.setLayout(new java.awt.BorderLayout());
        rightJPanel.add(objectListJPanel1, java.awt.BorderLayout.CENTER);

        add(rightJPanel, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vpl.gui.AddForceJPanel addForceJPanel1;
    private vpl.gui.AddObjectJPanel addObjectJPanel2;
    private javax.swing.JPanel centerJPanel;
    private vpl.gui.ExperimentExecutionJPanel experimentExecutionJPanel1;
    private vpl.gui.gl.VplGLCanvas glCanvas;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel leftJPanel;
    private vpl.gui.ObjectListJPanel objectListJPanel1;
    private javax.swing.JPanel rightJPanel;
    // End of variables declaration//GEN-END:variables
}
